### ISSUE TITLE
Incorrect trigger error when using of with multiple events

### ISSUE THREAD

**Issue by KevinSjoberg** [jenseng/hair_trigger#68]
I'm trying to port a trigger to `hair_trigger`. Unfortunately, it complains throwing the error:

    /usr/local/bundle/gems/hairtrigger-0.2.20/lib/hair_trigger/builder.rb:330:in `maybe_execute': of may only be specified on update triggers (HairTrigger::Builder::DeclarationError)

Here is the trigger in raw SQL:

```sql
CREATE FUNCTION toggle_current_role() RETURNS trigger as $toggle_current_role$
  BEGIN
    -- If row is current, do nothing.
    IF (TG_OP = 'UPDATE' AND OLD.current = true) THEN
      RETURN NEW;
    END IF;

    -- Ensure user roles are not marked as current
    UPDATE roles SET current = null WHERE current = true AND user_id = NEW.user_id;

    RETURN NEW;
  END;
$toggle_current_role$ LANGUAGE plpgsql;

CREATE TRIGGER toggle_current_role BEFORE INSERT OR UPDATE OF current ON roles
  FOR EACH ROW WHEN (NEW.current = true) EXECUTE PROCEDURE toggle_current_role();
```

In my model, I've written the trigger as follows:

```ruby
trigger.before(:insert, :update).of(:current).where('NEW.current = true') do
  <<-SQL
    -- If row is current, do nothing.
    IF (TG_OP = 'UPDATE' AND OLD.current = true) THEN
      RETURN NEW;
    END IF;

    -- Ensure user roles are not marked as current
    UPDATE roles SET current = null WHERE current = true AND user_id = NEW.user_id;

    RETURN NEW;
  SQL
end
```

This trigger is composed of two separate events. One `INSERT` and one `UPDATE OF`. `hair_trigger` does not distinguish this and complains since there are multiple events present.

**Comment by jenseng** [comment]
Thanks for the bug report @KevinSjoberg 👍 

Yeah, the assumption right now in the code is that all parts of the chain apply to the generated trigger(s), so it tries to apply the `of` to the `insert` trigger, which is not valid. Seems like to support this we'd need to change [this check](https://github.com/jenseng/hair_trigger/blob/89eefa2afdfaf6bec634bb9c411ce4500b8fcc97/lib/hair_trigger/builder.rb#L330) to something like:

```ruby
... if options[:of] && !(options[:events] || []).include?("UPDATE")
```

and also rework [this `generate_trigger_postgresql` logic](https://github.com/jenseng/hair_trigger/blob/89eefa2afdfaf6bec634bb9c411ce4500b8fcc97/lib/hair_trigger/builder.rb#L469), since it just blindly puts the OF clause after the events. I'd happily accept a pull request w/ a couple specs around it.

In the meantime, you could do something like this as a workaround:

```ruby
trigger_sql = <<-SQL
  -- If row is current, do nothing.
  IF (TG_OP = 'UPDATE' AND OLD.current = true) THEN
    RETURN NEW;
  END IF;

  -- Ensure user roles are not marked as current
  UPDATE roles SET current = null WHERE current = true AND user_id = NEW.user_id;

  RETURN NEW;
SQL
trigger.before(:insert).where('NEW.current') { trigger_sql }
trigger.before(:update).of(:current).where('NEW.current') { trigger_sql }
```

**Comment by KevinSjoberg** [comment]
@jenseng I'll take a look at this and see if I can submit a PR by the end of the week. 🙂

**Comment by KevinSjoberg** [comment]
@jenseng is this still an issue? I'm doing a bit of issue cleanup on my part.

**Comment by jenseng** [comment]
Hi @KevinSjoberg, I believe so, I haven't done anything with it yet. So I'll leave this issue open in case anyone else wants to take a stab at it.

I like to think I'll get to it eventually, but the reality is I write very little ruby these days and haven't used this gem in a project in years 😢

**Comment by KevinSjoberg** [comment]
@jenseng same here. I'll close it and let it resurface if needed.
